package bls_tss

import (
	"testing"

	"github.com/herumi/bls-eth-go-binary/bls"
)

func itorSigners(arr []string, k int) [][]string {
	var helper func(start int, combo []string)
	res := [][]string{}
	combo := []string{}

	helper = func(start int, combo []string) {
		if len(combo) == k {
			// Make a copy of combo since combo will be reused
			c := make([]string, len(combo))
			copy(c, combo)
			res = append(res, c)
			return
		}
		for i := start; i <= len(arr)-(k-len(combo)); i++ {
			// Add current element
			combo = append(combo, arr[i])
			// Move to the next element
			helper(i+1, combo)
			// Backtrack to try next candidate
			combo = combo[:len(combo)-1]
		}
	}

	helper(0, combo)
	return res
}

func TestSign(t *testing.T) {
	allId := []string{"1", "2", "3", "4", "5"}

	threshold := len(allId) - 2

	oirgVal := []byte("dfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasfdfasfasdfasf")
	verifyVal := oirgVal

	grp, err := NewSignerGroup(threshold, allId...)

	if err != nil {
		t.Error(err)
	}

	comb := itorSigners(allId, threshold)

	signValidator, err := RecoverSignerGroup(threshold, grp.GetPublicKeys(), []Signer{{}, {}, {}, {}, {}})
	if err != nil {
		t.Error(err)
	}

	for _, c := range comb {
		subGrp, err := grp.PickUpSigners(c...)
		if err != nil {
			t.Error(err)
		}
		sig, err := subGrp.Sign(oirgVal)
		if err != nil {
			t.Error(err)
		}
		s := sig.Serialize()
		dsig := &bls.Sign{}
		dsig.Deserialize(s)

		if !signValidator.Verify(dsig, verifyVal) {
			t.Error("Signature verification failed")
		}

		tmp := append(verifyVal, oirgVal...)
		if signValidator.Verify(dsig, tmp) {
			t.Error("Signature verification failed")
		}
	}
}
