web:
  port: 8080
db_connection: #
node:
  standalone: true # running as a single node, demo purpose
  genesis: true
  globalName: genesis-01
  externalAddr: "0.0.0.0"
  externalPort: 7946
  bindAddr: "0.0.0.0"
  bindPort: 7946
storage: another.dat
provider:
  alchemy: # ApiKey
api_key_access_enable: #true
chain_networks: # not supported in env, only in appsettings.yaml
  "ethereum-sepolia": | 
    {
      "chain_id": "11155111",
      "is_test": true,
      "v06_entrypoint_address" : "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
      "v07_entrypoint_address" : "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
      "v06_factory_address" : "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
      "v07_factory_address" : "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
      "rpc_url": "https://eth-sepolia.g.alchemy.com/v2/<API_KEY>"
    }
  "optimism-sepolia": |
    {
      "chain_id": "11155420",
      "is_test": true,
      "v06_entrypoint_address" : "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
      "v07_entrypoint_address" : "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
      "v06_factory_address" : "0x701678A4b5Acb4cD577e7de1AD574b2ea3e2Edeb",
      "v07_factory_address" : "0x701678A4b5Acb4cD577e7de1AD574b2ea3e2Edeb",
      "rpc_url": "https://opt-sepolia.g.alchemy.com/v2/<API_KEY>"
    }
  "base-sepolia": |
    {
      "chain_id": "84532",
      "is_test": true,
      "v06_entrypoint_address" : "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
      "v07_entrypoint_address" : "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
      "v06_factory_address" : "0x9406Cc6185a346906296840746125a0E44976454",
      "v07_factory_address" : "0x9406Cc6185a346906296840746125a0E44976454",
      "rpc_url": "https://base-sepolia.g.alchemy.com/v2/<API_KEY>"
    }
  "optimism-mainnet": |
    {
      "chain_id": "10",
      "is_test": false,
      "v06_entrypoint_address" : "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
      "v07_entrypoint_address" : "0x0000000071727De22E5E9d8BAf0edAc6f37da032",
      "v06_factory_address" : "0xF2147CA7f18e8014b76e1A98BaffC96ebB90a29f",
      "v07_factory_address": "0xF2147CA7f18e8014b76e1A98BaffC96ebB90a29f",
      "gas_token": "ETH",
      "token_config": {
        "USDT": "0x94b008aa00579c1307b0ef2c499ad98a8ce58e58",
        "USDC": "0x0b2c639c533813f4aa9d7837caf62653d097ff85"
      },
      "rpc_url": "https://opt-mainnet.g.alchemy.com/v2/<API_KEY>"
    }