web:
  port: 8080
db:
  user: # change it
  password: #change it
  host: #change it
  schema: aastar # db schema
jwt:
  security: thisisunsafeuntilyouchangit
  realm: AASTAR
  idkey: id
node:
  standalone: true # running as a single node, demo purpose
  genesis: true
  globalName: genesis-01
  externalAddr: "0.0.0.0"
  externalPort: 7946
  bindAddr: "0.0.0.0"
  bindPort: 7946
storage: another.dat
provider:
  alchemy: # ApiKey