basePath: /api
definitions:
  pkg.JsonRpcRequest:
    properties:
      id:
        type: integer
      jsonrpc:
        type: string
      method:
        type: string
      params:
        items: {}
        type: array
    type: object
  request.Bind:
    properties:
      account:
        type: string
      publicKey:
        type: string
    type: object
  request.Transfer:
    type: object
info:
  contact:
    name: AAStar Support
    url: https://aastar.xyz
paths:
  /api/account/v1/bind:
    post:
      consumes:
      - application/json
      description: bind a account to community node
      parameters:
      - description: Account Binding
        in: body
        name: bind
        required: true
        schema:
          $ref: '#/definitions/request.Bind'
      - description: apiKey
        in: query
        name: apiKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
      tags:
      - Account
  /api/account/v1/sign:
    post:
      consumes:
      - application/json
      description: sign a account to community node
      produces:
      - application/json
      responses:
        "201":
          description: Created
      tags:
      - Account
  /api/account/v1/transfer:
    post:
      consumes:
      - application/json
      description: transfer a TX
      parameters:
      - description: Transfer TX
        in: body
        name: tx
        required: true
        schema:
          $ref: '#/definitions/request.Transfer'
      - description: apiKey
        in: query
        name: apiKey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
      tags:
      - Account
  /api/dashboard/v1/node:
    get:
      consumes:
      - application/json
      description: get node members
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      tags:
      - Dashboard
  /api/healthz:
    get:
      consumes:
      - application/json
      description: Get Healthz
      responses:
        "200":
          description: OK
      tags:
      - Healthz
  /api/v1/airaccount_rpc/{network}:
    post:
      consumes:
      - application/json
      description: Airaccount JSON-RPC API
      parameters:
      - description: Network
        in: path
        name: network
        required: true
        type: string
      - description: JsonRpcRequest Model
        in: body
        name: rpcRequest
        required: true
        schema:
          $ref: '#/definitions/pkg.JsonRpcRequest'
      - description: apiKey
        in: query
        name: apiKey
        required: true
        type: string
      responses:
        "200":
          description: OK
      tags:
      - JsonRpcHandle
swagger: "2.0"
