definitions:
  request.Bind:
    properties:
      account:
        type: string
      publicKey:
        type: string
    type: object
  request.ClientCredential:
    properties:
      apiKey:
        type: string
    type: object
info:
  contact:
    name: AAStar Support
    url: https://aastar.xyz
paths:
  /api/account/v1/bind:
    post:
      consumes:
      - application/json
      description: bind a account to community node
      parameters:
      - description: Account Binding
        in: body
        name: bind
        required: true
        schema:
          $ref: '#/definitions/request.Bind'
      produces:
      - application/json
      responses:
        "201":
          description: Created
      security:
      - JWT: []
      tags:
      - Account
  /api/auth/v1/login:
    post:
      consumes:
      - application/json
      description: Get AccessToken By ApiKey
      parameters:
      - description: AccessToken Model
        in: body
        name: credential
        required: true
        schema:
          $ref: '#/definitions/request.ClientCredential'
      responses:
        "201":
          description: Created
      tags:
      - Auth
  /api/dashboard/v1/node:
    get:
      consumes:
      - application/json
      description: get node members
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      tags:
      - Dashboard
securityDefinitions:
  JWT:
    description: Type 'Bearer \<TOKEN\>' to correctly set the AccessToken
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
