name: Test and Coverage

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: Go Module Downloads
        run: go mod download
      - name: Run coverage
        run: go test -test.short -race -coverprofile=coverage.txt -covermode=atomic ./...
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{secrets.CODECOV_TOKEN}}
      #     slug: AAStarCommunity/AnotherAirAccountCommunityNode
